### ISSUE TITLE
Rent car

### ISSUE THREAD

**Issue by KevinTorp** [thor2304/HapticEngines#12]
Create the functionality needed for a user to be able to rent a specific car.
Ensure that the user gets a confirmation box before the user rents the car

Dates: From -> To
Userid: who rents it 
Carid: which car is getting rented

If db gets setup:
Ensure the car gets rented in the database so no other user can rent the same car (in the same period)

**Comment by thor2304** [comment]
The db has an endpoint that accepts post requests for rentals. This can be used to create new rentals.
The API spec is not updated for this yet, but it will be soon TM.
