### ISSUE TITLE
Backend setup

### ISSUE THREAD

**Issue by TobiasBak** [thor2304/HapticEngines#2]
The app needs a simple backend service.
The backend should expose the following endpoints:
- `/cars`
  - Returns the data of all cars. Possibly in the form of an array
- `/cars/hash`
  - Provides a hash of the array of the cars. Can be used to detect changes in available cars with minimal data transfer
- `/car/{carId}`
  - Returns detailed information on a single car
- `/images/{imageId}`
  - Returns the image with the given Id
- `/user/{userId}`
  - Provides profile information on a single user (This should probably be secured in some way for a real world setting) 

For each endpoint there should be a specification of the structure of the data.
A corresponding specification should be provided as a TypeScript type.

- [x] Create data model/specification (Diagram/textual version)
- [x] Expose endpoints in backend
- [x] Implement data model on backend
- [x] Implement data model as typescript type

At first the backend should be static and always provide the same results.

**Comment by thor2304** [comment]
https://app.swaggerhub.com/apis-docs/thor2304/MobileBackend/1.0.0
https://app.swaggerhub.com/apis/thor2304/MobileBackend/1.0.0#/Users/getUserById

**Comment by thor2304** [comment]
Remember to rewrite the API spec, so it matches completely with the finished result of the backend. The following items will likely need a small update:
- Data types for post endpoints
- Possible data types for the image endpoint
- Response codes for the post endpoints (unless i do it properly on the backend, if any of you see this, feel free to add a comment on how advanced you want the backend)

**Comment by thor2304** [comment]
https://laravel.com/docs/10.x/eloquent-serialization#serializing-models-and-collections
https://laravel.com/docs/10.x/eloquent-resources
https://laravel.com/docs/8.x/eloquent-relationships
