### ISSUE TITLE
Discovery screen

### ISSUE THREAD

**Issue by TobiasBak** [thor2304/HapticEngines#3]
The layout of the discovery screen and rendering images from the backend, excluding the functionality of the search bar #10 (But create it in the layout still)
![image](https://github.com/thor2304/HapticEngines/assets/49482313/cd69e951-318f-4aa9-bb2c-075d95574f3c)

**Comment by schwartz21** [comment]
Important: Map the model from DB using the method in the following link: 
https://github.com/dayitv89/react-native-jsmodel
