### ISSUE TITLE
Car details screen

### ISSUE THREAD

**Issue by TobiasBak** [thor2304/HapticEngines#4]
Tasks for this screen:
- [x] Use the BackendHandler to fetch cars from the DB
- [x] Create slider view where you can scroll through the list of cars
- [x] Create info view that shows price and details of the car
- [x] Create a rent button

This is the screen that looks like:
![image](https://github.com/thor2304/HapticEngines/assets/49482313/c6d8dce1-aa60-4aaf-bc02-8f16e4be5dfe)

The images can be retrieved from a backend endpoint specified in #2

**Comment by schwartz21** [comment]
Important: Map the model from DB using the method in the following link:
https://github.com/dayitv89/react-native-jsmodel

**Comment by schwartz21** [comment]
Tasks for this screen:
- [ ] Do something

**Comment by thor2304** [comment]
Changed description to use the BackendHandler instead of creating the function for retrieving images
