### ISSUE TITLE
Profile screen

### ISSUE THREAD

**Issue by TobiasBak** [thor2304/HapticEngines#5]
![image](https://github.com/thor2304/HapticEngines/assets/49482313/c5318826-f2bf-422a-8ae0-7b6d541152d8)

**Comment by schwartz21** [comment]
Important: Map the model from DB using the method in the following link:
https://github.com/dayitv89/react-native-jsmodel

**Comment by Rachristi** [comment]
Dark Theme that has been added must be added in the design documentation.
