### ISSUE TITLE
Notification system

### ISSUE THREAD

**Issue by TobiasBak** [thor2304/HapticEngines#7]
When the available cars change, a push notification should be triggered. See #2 

This can be measured in a performance requirement, so we should choose the polling time carefully. Consider whether we can use websockets in the background job. That might be more efficient than polling (And lower latency)

Consider whether we should create a proper framework for notifications, where the backend can "create" notifications on a channel for the user to read. I am thinking something like:
- `/notifications/latest`
  - Provides the id of the latest notification
- `/notifications/{notificationId}`
  - Returns the notification to be displayed

This has a host of issues (How to differentiate between different users? Confidentiality? etc.) But if it sounds interesting use it as a starting point.

**Comment by thor2304** [comment]
Useful Ressources:
https://docs.expo.dev/versions/latest/sdk/background-fetch/ 

https://docs.expo.dev/versions/latest/sdk/notifications/
